server:
  port: 9000
  servlet:
    context-path: /api/v1
logging:
  level:
    org.springframework.security: trace

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5444/ships
    username: admin
    password: topSecret
  web:
    resources:
      static-locations:
        "../images"
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
httpService:
   uri:
    azur-api-url: https://raw.githubusercontent.com/AzurAPI/azurapi-js-setup/master